---
abstract: 'Class for SysV init service manipulation.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.07
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SysV-Init-Service
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Utils: 0.05
  English: 0
  Error::Pure: 0.14
  File::Spec::Functions: 0
  IO::CaptureOutput: 0
  List::MoreUtils: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=SysV-Init-Service
  homepage: https://github.com/tupinek/SysV-Init-Service
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/SysV-Init-Service
version: 0.03
