---
abstract: 'Class for SysV init service manipulation.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.07
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SysV-Init-Service
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Capture::Tiny: 0
  Class::Utils: 0.05
  English: 0
  Error::Pure: 0.15
  File::Spec::Functions: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/SysV-Init-Service/issues
  homepage: https://github.com/michal-josef-spacek/SysV-Init-Service
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/SysV-Init-Service
version: '0.08'
